#############################################################################
# Makefile for building: DnD.app/Contents/MacOS/DnD
# Generated by qmake (2.01a) (Qt 4.6.3) on: Mon Nov 29 20:53:43 2010
# Project:  DnD.pro
# Template: app
# Command: /opt/local/bin/qmake -macx -o Makefile DnD.pro
#############################################################################

####### Compiler, tools and options

CC            = /usr/bin/gcc-4.2
CXX           = /usr/bin/g++-4.2
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/opt/local/libexec/qt4-mac/mkspecs/macx-g++ -I. -I/opt/local/libexec/qt4-mac/lib/QtCore.framework/Versions/4/Headers -I/opt/local/libexec/qt4-mac/lib/QtCore.framework/Versions/4/Headers -I/opt/local/libexec/qt4-mac/lib/QtGui.framework/Versions/4/Headers -I/opt/local/libexec/qt4-mac/lib/QtGui.framework/Versions/4/Headers -I/opt/local/libexec/qt4-mac/include -I. -I. -F/opt/local/libexec/qt4-mac/lib
LINK          = /usr/bin/g++-4.2
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/opt/local/libexec/qt4-mac/lib -L/opt/local/libexec/qt4-mac/lib -framework QtGui -L/opt/local/libexec/qt4-mac/lib -F/opt/local/libexec/qt4-mac/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /opt/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = dateedit.cpp \
		dragwidget.cpp \
		editor.cpp \
		hotspot.cpp \
		lineedit.cpp \
		main.cpp \
		templatewidget.cpp \
		textedit.cpp moc_dragwidget.cpp \
		moc_templatewidget.cpp \
		qrc_draggabletext.cpp
OBJECTS       = dateedit.o \
		dragwidget.o \
		editor.o \
		hotspot.o \
		lineedit.o \
		main.o \
		templatewidget.o \
		textedit.o \
		moc_dragwidget.o \
		moc_templatewidget.o \
		qrc_draggabletext.o
DIST          = /opt/local/libexec/qt4-mac/mkspecs/common/unix.conf \
		/opt/local/libexec/qt4-mac/mkspecs/common/mac.conf \
		/opt/local/libexec/qt4-mac/mkspecs/common/mac-g++.conf \
		/opt/local/libexec/qt4-mac/mkspecs/qconfig.pri \
		/opt/local/libexec/qt4-mac/mkspecs/features/qt_functions.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/qt_config.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/exclusive_builds.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/default_pre.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/default_pre.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/release.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/default_post.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/default_post.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/x86_64.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/objective_c.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/warn_on.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/qt.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/unix/thread.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/moc.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/rez.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/sdk.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/resources.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/uic.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/yacc.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/lex.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/include_source_dir.prf \
		DnD.pro
QMAKE_TARGET  = DnD
DESTDIR       = 
TARGET        = DnD.app/Contents/MacOS/DnD

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile DnD.app/Contents/PkgInfo DnD.app/Contents/Resources/empty.lproj DnD.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) DnD.app/Contents/MacOS/ || $(MKDIR) DnD.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DnD.pro  /opt/local/libexec/qt4-mac/mkspecs/macx-g++/qmake.conf /opt/local/libexec/qt4-mac/mkspecs/common/unix.conf \
		/opt/local/libexec/qt4-mac/mkspecs/common/mac.conf \
		/opt/local/libexec/qt4-mac/mkspecs/common/mac-g++.conf \
		/opt/local/libexec/qt4-mac/mkspecs/qconfig.pri \
		/opt/local/libexec/qt4-mac/mkspecs/features/qt_functions.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/qt_config.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/exclusive_builds.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/default_pre.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/default_pre.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/release.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/default_post.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/default_post.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/x86_64.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/objective_c.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/warn_on.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/qt.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/unix/thread.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/moc.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/rez.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/sdk.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/resources.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/uic.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/yacc.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/lex.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/include_source_dir.prf \
		/opt/local/libexec/qt4-mac/lib/QtGui.framework/QtGui.prl \
		/opt/local/libexec/qt4-mac/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -macx -o Makefile DnD.pro
/opt/local/libexec/qt4-mac/mkspecs/common/unix.conf:
/opt/local/libexec/qt4-mac/mkspecs/common/mac.conf:
/opt/local/libexec/qt4-mac/mkspecs/common/mac-g++.conf:
/opt/local/libexec/qt4-mac/mkspecs/qconfig.pri:
/opt/local/libexec/qt4-mac/mkspecs/features/qt_functions.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/qt_config.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/exclusive_builds.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/default_pre.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/default_pre.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/release.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/default_post.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/default_post.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/x86_64.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/objective_c.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/warn_on.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/qt.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/unix/thread.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/moc.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/rez.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/sdk.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/resources.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/uic.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/yacc.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/lex.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/include_source_dir.prf:
/opt/local/libexec/qt4-mac/lib/QtGui.framework/QtGui.prl:
/opt/local/libexec/qt4-mac/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -macx -o Makefile DnD.pro

DnD.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) DnD.app/Contents || $(MKDIR) DnD.app/Contents 
	@$(DEL_FILE) DnD.app/Contents/PkgInfo
	@echo "APPL????" >DnD.app/Contents/PkgInfo
DnD.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) DnD.app/Contents/Resources || $(MKDIR) DnD.app/Contents/Resources 
	@touch DnD.app/Contents/Resources/empty.lproj
	
DnD.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) DnD.app/Contents || $(MKDIR) DnD.app/Contents 
	@$(DEL_FILE) DnD.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,DnD,g" -e "s,@TYPEINFO@,????,g" /opt/local/libexec/qt4-mac/mkspecs/macx-g++/Info.plist.app >DnD.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/DnD1.0.0 || $(MKDIR) .tmp/DnD1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/DnD1.0.0/ && $(COPY_FILE) --parents action.h dateedit.h dragwidget.h editor.h hotspot.h lineedit.h templatewidget.h textedit.h .tmp/DnD1.0.0/ && $(COPY_FILE) --parents draggabletext.qrc .tmp/DnD1.0.0/ && $(COPY_FILE) --parents dateedit.cpp dragwidget.cpp editor.cpp hotspot.cpp lineedit.cpp main.cpp templatewidget.cpp textedit.cpp .tmp/DnD1.0.0/ && (cd `dirname .tmp/DnD1.0.0` && $(TAR) DnD1.0.0.tar DnD1.0.0 && $(COMPRESS) DnD1.0.0.tar) && $(MOVE) `dirname .tmp/DnD1.0.0`/DnD1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/DnD1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r DnD.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_dragwidget.cpp moc_templatewidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dragwidget.cpp moc_templatewidget.cpp
moc_dragwidget.cpp: templatewidget.h \
		editor.h \
		hotspot.h \
		action.h \
		dateedit.h \
		dragwidget.h
	/opt/local/libexec/qt4-mac/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ dragwidget.h -o moc_dragwidget.cpp

moc_templatewidget.cpp: editor.h \
		templatewidget.h
	/opt/local/libexec/qt4-mac/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ templatewidget.h -o moc_templatewidget.cpp

compiler_rcc_make_all: qrc_draggabletext.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_draggabletext.cpp
qrc_draggabletext.cpp: draggabletext.qrc \
		words.txt
	/opt/local/libexec/qt4-mac/bin/rcc -name draggabletext draggabletext.qrc -o qrc_draggabletext.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

dateedit.o: dateedit.cpp dateedit.h \
		editor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dateedit.o dateedit.cpp

dragwidget.o: dragwidget.cpp textedit.h \
		templatewidget.h \
		editor.h \
		lineedit.h \
		dragwidget.h \
		hotspot.h \
		action.h \
		dateedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dragwidget.o dragwidget.cpp

editor.o: editor.cpp editor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editor.o editor.cpp

hotspot.o: hotspot.cpp hotspot.h \
		action.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hotspot.o hotspot.cpp

lineedit.o: lineedit.cpp lineedit.h \
		templatewidget.h \
		editor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lineedit.o lineedit.cpp

main.o: main.cpp dragwidget.h \
		templatewidget.h \
		editor.h \
		hotspot.h \
		action.h \
		dateedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

templatewidget.o: templatewidget.cpp templatewidget.h \
		editor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o templatewidget.o templatewidget.cpp

textedit.o: textedit.cpp textedit.h \
		templatewidget.h \
		editor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textedit.o textedit.cpp

moc_dragwidget.o: moc_dragwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dragwidget.o moc_dragwidget.cpp

moc_templatewidget.o: moc_templatewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_templatewidget.o moc_templatewidget.cpp

qrc_draggabletext.o: qrc_draggabletext.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_draggabletext.o qrc_draggabletext.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

